### ISSUE TITLE
dvo_slam runtime problem 

### ISSUE THREAD

**Issue by lynnsky** [tum-vision/dvo#13]
I have many problems.I am a newer.
I take the usage as https://github.com/tum-vision/dvo told
1.when run_dense_tracking is selected,rosrun dvo_ros camera_tracker go wrong.segment fault.
gdb -ex run --args ./bin/camera_tracker
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xa9768b40 (LWP 13993)]
0xb76a2208 in dvo::core::SurfacePyramid::convertRawDepthImageSse(cv::Mat const&, cv::Mat&, float) ()
from /home/lynn/fuerte_workspace/sandbox/dvo_slam/dvo_core/lib/libdvo_core.so
(gdb)
2.I cannot changed the reference frame to /world,because i cannot find the /world,
3.I still donot know how to to run dvo_slam on datasets.
I cannot rosrun rgbd_benchmark_tool associate.py rgb.txt depth.txt > assoc.txt.
because i donot have rgbd_benchmark_tool .
so i run python associate.py rgb.txt depth.txt > assoc.txt.,get the assoc.txt file
roslaunch dvo_benchmark benchmark.launch dataset:=/path/to/dataset keep_alive:=true
it get wrong as follows:
benchmark: /usr/include/eigen3/Eigen/src/Core/DenseStorage.h:69: Eigen::internal::plain_array::plain_array() [with T = double, int Size = 16, int MatrixOrArrayOptions = 0]: Assertion `(reinterpret_cast(array) & 0xf) == 0 && "this assertion is explained here: " "http://eigen.tuxfamily.org/dox-devel/TopicUnalignedArrayAssert.html" " ***\* READ THIS WEB PAGE !!! ***_"' failed.
[benchmark-1] process has died [pid 12411, exit code -6, cmd /home/lynn/fuerte_workspace/sandbox/dvo_slam/dvo_benchmark/bin/benchmark __name:=benchmark __log:=/home/lynn/.ros/log/2091290c-6ec9-11e4-82d1-c0cb386b60af/benchmark-1.log].
log file: /home/lynn/.ros/log/2091290c-6ec9-11e4-82d1-c0cb386b60af/benchmark-1_.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
done
I cannot come up with any idea.

**Comment by egoist-sx** [comment]
Same issues encountered

**Comment by mariusschweizer1** [comment]
Hello

I use ROS Kinetic, Ubuntu16.04 and a Kinect ONE and followed the instructions https://github.com/tum-vision/dvo_slam/tree/kinetic-devel
rosmake has succesfully worked and now i tried to launch dvo_benchmark.
When i roslaunch dvo_benchmark benchmark.launch keep_alive:=true, the assoc.txt is missing.

I have the same Problem that rgbd_benchmark_tools is not available to create the assoc.txt file.
How can i solve this problem or where i get this tool?

I hope some one can help me please

Marius
