### ISSUE TITLE
No pose change

### ISSUE THREAD

**Issue by aswinthomas** [tum-vision/dvo#5]
Hi,
I am trying to get the odometry running using my kinect. Following is my launch file:
https://dl.dropboxusercontent.com/u/8948006/dvo_odo.launch

Openni is already sending depth registered images.

I also modified CameraBase constructor to update topic names:
  rgb_image_subscriber_(nh, "camera/rgb/image_rect_mono", 1),
  depth_image_subscriber_(nh, "/camera/depth_registered/hw_registered/image_rect_raw", 1),
  rgb_camera_info_subscriber_(nh, "camera/rgb/camera_info", 1),
  depth_camera_info_subscriber_(nh, "camera/depth_registered/camera_info", 1),

I am able to see "camera/rgb/image_rect_mono" and "/camera/depth_registered/hw_registered/image_rect_raw" in rviz. I can also view pointcloud published "/cloud" and pose ("/rgbd/pose"). However the pose does not change when I move the kinect. It constantly has a short high frequency vibration. 

Output of running the launch file:
started roslaunch server http://192.168.1.13:56013/

SUMMARY

PARAMETERS
- /camera_tracker/reconstruction
- /camera_tracker/run_dense_tracking
- /camera_tracker/use_dense_tracking_estimate
- /camera_tracker/use_weighting
- /rosdistro
- /rosversion

NODES
  /
    camera_tracker (dvo_ros/camera_tracker)

ROS_MASTER_URI=http://localhost:11311/

core service [/rosout] found
process[camera_tracker-1]: started with pid [20215]
CameraDenseTracker::ctor(...)
config.run_dense_tracking:1 config.use_dense_tracking_estimate:1
reconfigured tracker, config ( First Level = 3, Last Level = 1, Max Iterations per Level = 50, Precision = 0.0001, Mu = 0, Use Initial Estimate = true, Use Weighting = true, Scale Estimator = TDistribution, Scale Estimator Param = 5, Influence Function = TDistribution, Influence Function Param = 5, Intensity Derivative Threshold = 0, Depth Derivative Threshold = 0 )
using identity!
transformation: base_link -> asus
1 0 0 0
0 1 0 0
0 0 1 0
0 0 0 1
started camera_tracker...
RGB image size has changed, resetting tracker!
x:0.00 y:0.00 z:0.00 roll:0.00 pitch:0.00 yaw:-0.00
match: 0.00801919
x:0.00 y:-0.00 z:-0.00 roll:0.00 pitch:-0.00 yaw:-0.00
match: 0.00740023
x:0.00 y:-0.00 z:-0.00 roll:0.00 pitch:-0.00 yaw:-0.00
match: 0.00765328
match: 0.00754171
x:0.00 y:-0.01 z:-0.00 roll:0.00 pitch:-0.00 yaw:-0.00
match: 0.0076491
callback: 0.00965808
x:0.00 y:0.01 z:0.00 roll:0.00 pitch:0.00 yaw:-0.00
match: 0.00582242
match: 0.00827256
x:0.00 y:0.01 z:0.00 roll:0.00 pitch:0.00 yaw:-0.00
match: 0.00754653
x:0.00 y:0.01 z:0.00 roll:0.00 pitch:0.00 yaw:-0.00
match: 0.00619464
match: 0.0062666
callback: 0.00881737
x:0.00 y:0.01 z:0.00 roll:0.00 pitch:0.00 yaw:-0.00
match: 0.00645015
x:0.00 y:0.01 z:0.00 roll:0.00 pitch:0.00 yaw:-0.00
match: 0.00671455
match: 0.00644076
x:0.00 y:0.02 z:0.00 roll:0.00 pitch:0.00 yaw:-0.00
match: 0.00683598
x:0.00 y:-0.02 z:-0.00 roll:0.00 pitch:-0.00 yaw:-0.00
match: 0.00648071
callback: 0.00843992
match: 0.00684254
x:0.00 y:-0.02 z:-0.00 roll:0.00 pitch:-0.00 yaw:-0.00
match: 0.00710994
x:0.00 y:0.02 z:0.00 roll:0.00 pitch:0.00 yaw:-0.00
match: 0.00689754
match: 0.00664394
x:0.00 y:0.02 z:0.00 roll:0.00 pitch:0.00 yaw:-0.00
match: 0.00658692
callback: 0.00886757
...................

I printed out x,y,z to view the values, but no change. Any advice is appreciated.

Cheers
Aswin

**Comment by christiankerl** [comment]
is your depth image topic in uint16 format? does the camera_info topic provide the correct parameters or at least any parameters?

**Comment by aswinthomas** [comment]
Thank you for your reply. The topic camera/depth_registered/hw_registered/image_rect_raw doesnt seem to correspond to the image topic camera/depth_registered/camera_info. I used camera/depth_registered/image_raw and it finally works now. Thank you.
